@echo off 
cd baseline-mmin
set seed[0]=1234 
set seed[1]=9138
set seed[2]=86503
set seed[3]=37949
set seed[4]=22627
set seed[5]=75258
set seed[6]=94877
set seed[7]=9829
set seed[8]=47702
set seed[9]=15908

python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=1234 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9138 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=86503 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=37949 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=22627 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=75258 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=94877 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9829 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=47702 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.1  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=15908 --output logMMIM.txt

python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=1234 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9138 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=86503 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=37949 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=22627 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=75258 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=94877 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9829 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=47702 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.2  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=15908 --output logMMIM.txt

python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=1234 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9138 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=86503 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=37949 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=22627 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=75258 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=94877 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9829 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=47702 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.3  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=15908 --output logMMIM.txt

python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=1234 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9138 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=86503 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=37949 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=22627 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=75258 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=94877 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9829 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=47702 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.4  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=15908 --output logMMIM.txt

python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=1234 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9138 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=86503 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=37949 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=22627 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=75258 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=94877 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9829 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=47702 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.5  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=15908 --output logMMIM.txt

python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=1234 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9138 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=86503 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=37949 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=22627 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=75258 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=94877 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=9829 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=47702 --output logMMIM.txt
python train_baseline.py --dataset_mode=cmumosi_multimodal --mask_rate=0.66  --model=mmin --gpu_ids=0 --log_dir=./logs --checkpoints_dir=./checkpoints --print_freq=10 --input_dim_a=250 --embd_size_a=128 --input_dim_v=1000 --embd_size_v=128 --input_dim_l=38400 --embd_size_l=128 --cls_layers=128,128 --dropout_rate=0.3 --niter=20 --niter_decay=30 --beta1=0.9 --init_type kaiming --batch_size=1 --lr=1e-3 --run_idx=8 --name=mmin --suffix=cmumosi_MMINTemp  --output_dim=1 --pretrained_path checkpoints/utt_fusion_cmumosi_AVL --seed=15908 --output logMMIM.txt



cd ..